# Meta
description: A minimal hexo theme.
keywords: hexo,theme,typescript,otakism,otaku
site_desc: otaku keeps alive

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: About
  slug: about
  url: /about
- name: Archives
  slug: archives
  url: /archives

# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics:
favicon: /favicon.png
author_url: https://kntan.coding.me

# Less
less:
  compress: true

# use url, not username
social:
- slug: email
  url: #mailto:stkevintan@zju.edu.cn
- slug: github
  url: https://github.com/stkevintan
- slug: twitter
  url: https://twitter.com/kevinclasky
- slug: rss
	url: /atom.xml
# - slug: google
#   url: https://plus.google.com/u/0/116188417424462670099
# - slug: facebook
#   url: # https://www.facebook.com/
# - slug: linkedin
#   url: # https://www.linkedin.com/
# - slug: sina-weibo
#   url: http://weibo.com/kevinclasky
# - slug: tumblr
#   url: # http://artchen.tumblr.com
# - slug: dribbble
#   url: # https://dribbble.com/artchen
# - slug: pinterest
#   url: # https://www.pinterest.com/otakism/
# - slug: instagram
#   url: # https://instagram.com/otakism/
# - slug: behance
#   url: # https://www.behance.net/artchen